language: python

python:
- "2.7"

# The secure env variables are: GEMFURY_KEY
env:
  global:
    - secure: "SngxntTzhU40H9NXL5obpQz3YZTAF1TOqkFjapzoU22dVcS6kYwK5Fs9uu2b5p3NMYcThY4ZbY/XvGm2JVSGf7DAkDINAI17U7Q+FdI9avNzB9c5oOh2c0mlfS2St4kZ2e8CO73zO210uBavL/cT4pW2F0TI3JdOE6lKxj6JykfBL2fd6vzjKnxoXAaDSpYU68yvZECEshVwFgaz3/ISEXfMrwjxdrC7wqAG5nuxtyYDkqu2mljEB9GMIH3pgJlDqnx0PpM/dR4w1bFlUgq14EsN/0jTygA2eZEXmK4ezVZFH/NZksoUiLXQHV257jZg5LgO/neaOSbp69nnxKJlHrOtkycAIQPgentHmXJKbY8zZZvoF7zjr6IfqwhBm237AdACRX1+YlIhtSZ+qTQVF1r1VwuOZgerFimsIgMmeugw2JiouOp5J0r/SFbJw13hLsY4mbPbl+9xXCpEgsB0Xv8M60ROADcuBXGFY4SvAp99JSo0Bl2umpPCzFt11uhfc7cdordKNaOxndHVzfcuzl2mslOKCzK3/AwT5gtcItveUeTO1U2LHNXBAHp6TsH/nqrqv860J9lhBd1OKvv54jEM9E3WMdErNXIrCR54AGMwoNj0hqsg2+WPba6X7uOLSWWMKwXLb9uo0y1t2aoI1zBRo03cxQMT1xl3jJLkH4A="

install: 
  - pip install coveralls
  - pip install coverage
  - pip install -r requirements.txt

script: coverage run --module unittest discover --verbose

after_success:
  - coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: bin/togemfury.sh

sudo: false
